// Shared types for the uniclient bridge layer.
// Generated from go/cores/base.go — keep in sync.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/models.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	ChatType_CHAT_TYPE_UNSPECIFIED ChatType = 0
	ChatType_CHAT_TYPE_DM          ChatType = 1
	ChatType_CHAT_TYPE_GROUP       ChatType = 2
	ChatType_CHAT_TYPE_CHANNEL     ChatType = 3
	ChatType_CHAT_TYPE_TOPIC       ChatType = 4
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "CHAT_TYPE_UNSPECIFIED",
		1: "CHAT_TYPE_DM",
		2: "CHAT_TYPE_GROUP",
		3: "CHAT_TYPE_CHANNEL",
		4: "CHAT_TYPE_TOPIC",
	}
	ChatType_value = map[string]int32{
		"CHAT_TYPE_UNSPECIFIED": 0,
		"CHAT_TYPE_DM":          1,
		"CHAT_TYPE_GROUP":       2,
		"CHAT_TYPE_CHANNEL":     3,
		"CHAT_TYPE_TOPIC":       4,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_proto_models_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{0}
}

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_SENDING     MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_DELIVERED   MessageStatus = 3
	MessageStatus_MESSAGE_STATUS_READ        MessageStatus = 4
	MessageStatus_MESSAGE_STATUS_FAILED      MessageStatus = 5
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_SENDING",
		2: "MESSAGE_STATUS_SENT",
		3: "MESSAGE_STATUS_DELIVERED",
		4: "MESSAGE_STATUS_READ",
		5: "MESSAGE_STATUS_FAILED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_SENDING":     1,
		"MESSAGE_STATUS_SENT":        2,
		"MESSAGE_STATUS_DELIVERED":   3,
		"MESSAGE_STATUS_READ":        4,
		"MESSAGE_STATUS_FAILED":      5,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_proto_enumTypes[1].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_proto_models_proto_enumTypes[1]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{1}
}

type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNSPECIFIED    UpdateType = 0
	UpdateType_UPDATE_TYPE_NEW_MESSAGE    UpdateType = 1
	UpdateType_UPDATE_TYPE_EDIT_MESSAGE   UpdateType = 2
	UpdateType_UPDATE_TYPE_DELETE_MESSAGE UpdateType = 3
	UpdateType_UPDATE_TYPE_READ_STATE     UpdateType = 4
	UpdateType_UPDATE_TYPE_USER_STATUS    UpdateType = 5
	UpdateType_UPDATE_TYPE_TYPING         UpdateType = 6
	UpdateType_UPDATE_TYPE_CALL_STATE     UpdateType = 7
	UpdateType_UPDATE_TYPE_GROUP_MEMBERS  UpdateType = 8
	UpdateType_UPDATE_TYPE_VERIFICATION   UpdateType = 9
	UpdateType_UPDATE_TYPE_CONNECTIVITY   UpdateType = 10
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0:  "UPDATE_TYPE_UNSPECIFIED",
		1:  "UPDATE_TYPE_NEW_MESSAGE",
		2:  "UPDATE_TYPE_EDIT_MESSAGE",
		3:  "UPDATE_TYPE_DELETE_MESSAGE",
		4:  "UPDATE_TYPE_READ_STATE",
		5:  "UPDATE_TYPE_USER_STATUS",
		6:  "UPDATE_TYPE_TYPING",
		7:  "UPDATE_TYPE_CALL_STATE",
		8:  "UPDATE_TYPE_GROUP_MEMBERS",
		9:  "UPDATE_TYPE_VERIFICATION",
		10: "UPDATE_TYPE_CONNECTIVITY",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNSPECIFIED":    0,
		"UPDATE_TYPE_NEW_MESSAGE":    1,
		"UPDATE_TYPE_EDIT_MESSAGE":   2,
		"UPDATE_TYPE_DELETE_MESSAGE": 3,
		"UPDATE_TYPE_READ_STATE":     4,
		"UPDATE_TYPE_USER_STATUS":    5,
		"UPDATE_TYPE_TYPING":         6,
		"UPDATE_TYPE_CALL_STATE":     7,
		"UPDATE_TYPE_GROUP_MEMBERS":  8,
		"UPDATE_TYPE_VERIFICATION":   9,
		"UPDATE_TYPE_CONNECTIVITY":   10,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_proto_enumTypes[2].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_proto_models_proto_enumTypes[2]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{2}
}

type CallState int32

const (
	CallState_CALL_STATE_UNSPECIFIED CallState = 0
	CallState_CALL_STATE_RINGING     CallState = 1
	CallState_CALL_STATE_CONNECTING  CallState = 2
	CallState_CALL_STATE_ACTIVE      CallState = 3
	CallState_CALL_STATE_ENDED       CallState = 4
)

// Enum value maps for CallState.
var (
	CallState_name = map[int32]string{
		0: "CALL_STATE_UNSPECIFIED",
		1: "CALL_STATE_RINGING",
		2: "CALL_STATE_CONNECTING",
		3: "CALL_STATE_ACTIVE",
		4: "CALL_STATE_ENDED",
	}
	CallState_value = map[string]int32{
		"CALL_STATE_UNSPECIFIED": 0,
		"CALL_STATE_RINGING":     1,
		"CALL_STATE_CONNECTING":  2,
		"CALL_STATE_ACTIVE":      3,
		"CALL_STATE_ENDED":       4,
	}
)

func (x CallState) Enum() *CallState {
	p := new(CallState)
	*p = x
	return p
}

func (x CallState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_proto_enumTypes[3].Descriptor()
}

func (CallState) Type() protoreflect.EnumType {
	return &file_proto_models_proto_enumTypes[3]
}

func (x CallState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallState.Descriptor instead.
func (CallState) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{3}
}

type AuthMode int32

const (
	AuthMode_AUTH_MODE_UNSPECIFIED AuthMode = 0
	AuthMode_AUTH_MODE_BOT         AuthMode = 1
	AuthMode_AUTH_MODE_USER        AuthMode = 2
)

// Enum value maps for AuthMode.
var (
	AuthMode_name = map[int32]string{
		0: "AUTH_MODE_UNSPECIFIED",
		1: "AUTH_MODE_BOT",
		2: "AUTH_MODE_USER",
	}
	AuthMode_value = map[string]int32{
		"AUTH_MODE_UNSPECIFIED": 0,
		"AUTH_MODE_BOT":         1,
		"AUTH_MODE_USER":        2,
	}
)

func (x AuthMode) Enum() *AuthMode {
	p := new(AuthMode)
	*p = x
	return p
}

func (x AuthMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_models_proto_enumTypes[4].Descriptor()
}

func (AuthMode) Type() protoreflect.EnumType {
	return &file_proto_models_proto_enumTypes[4]
}

func (x AuthMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMode.Descriptor instead.
func (AuthMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{4}
}

type AuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          AuthMode               `protobuf:"varint,1,opt,name=mode,proto3,enum=uniclient.AuthMode" json:"mode,omitempty"`
	BotToken      string                 `protobuf:"bytes,2,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Otp           string                 `protobuf:"bytes,4,opt,name=otp,proto3" json:"otp,omitempty"`
	Password_2F   string                 `protobuf:"bytes,5,opt,name=password_2f,json=password2f,proto3" json:"password_2f,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_proto_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{0}
}

func (x *AuthConfig) GetMode() AuthMode {
	if x != nil {
		return x.Mode
	}
	return AuthMode_AUTH_MODE_UNSPECIFIED
}

func (x *AuthConfig) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *AuthConfig) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AuthConfig) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *AuthConfig) GetPassword_2F() string {
	if x != nil {
		return x.Password_2F
	}
	return ""
}

func (x *AuthConfig) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PaginationOpts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        string                 `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationOpts) Reset() {
	*x = PaginationOpts{}
	mi := &file_proto_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationOpts) ProtoMessage() {}

func (x *PaginationOpts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationOpts.ProtoReflect.Descriptor instead.
func (*PaginationOpts) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationOpts) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationOpts) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	AvatarB64     string                 `protobuf:"bytes,6,opt,name=avatar_b64,json=avatarB64,proto3" json:"avatar_b64,omitempty"`
	IsBot         bool                   `protobuf:"varint,7,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	IsOnline      bool                   `protobuf:"varint,8,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	LastSeenMs    int64                  `protobuf:"varint,9,opt,name=last_seen_ms,json=lastSeenMs,proto3" json:"last_seen_ms,omitempty"` // unix millis, 0 = unset
	Platform      string                 `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetAvatarB64() string {
	if x != nil {
		return x.AvatarB64
	}
	return ""
}

func (x *User) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *User) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *User) GetLastSeenMs() int64 {
	if x != nil {
		return x.LastSeenMs
	}
	return 0
}

func (x *User) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type Dialog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ChatType               `protobuf:"varint,2,opt,name=type,proto3,enum=uniclient.ChatType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	AvatarB64     string                 `protobuf:"bytes,5,opt,name=avatar_b64,json=avatarB64,proto3" json:"avatar_b64,omitempty"`
	LastMessage   *Message               `protobuf:"bytes,6,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,7,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	IsMuted       bool                   `protobuf:"varint,8,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsPinned      bool                   `protobuf:"varint,9,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	IsArchived    bool                   `protobuf:"varint,10,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	MemberCount   int32                  `protobuf:"varint,11,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	ParentId      string                 `protobuf:"bytes,12,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Platform      string                 `protobuf:"bytes,13,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dialog) Reset() {
	*x = Dialog{}
	mi := &file_proto_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dialog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dialog) ProtoMessage() {}

func (x *Dialog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dialog.ProtoReflect.Descriptor instead.
func (*Dialog) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{3}
}

func (x *Dialog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dialog) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_CHAT_TYPE_UNSPECIFIED
}

func (x *Dialog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Dialog) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Dialog) GetAvatarB64() string {
	if x != nil {
		return x.AvatarB64
	}
	return ""
}

func (x *Dialog) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *Dialog) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Dialog) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *Dialog) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *Dialog) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *Dialog) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Dialog) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Dialog) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName    string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // unix millis
	EditedAtMs    int64                  `protobuf:"varint,7,opt,name=edited_at_ms,json=editedAtMs,proto3" json:"edited_at_ms,omitempty"`  // 0 = not edited
	Status        MessageStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=uniclient.MessageStatus" json:"status,omitempty"`
	ReplyToId     string                 `protobuf:"bytes,9,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"`
	ReplyPreview  string                 `protobuf:"bytes,10,opt,name=reply_preview,json=replyPreview,proto3" json:"reply_preview,omitempty"`
	ForwardFrom   string                 `protobuf:"bytes,11,opt,name=forward_from,json=forwardFrom,proto3" json:"forward_from,omitempty"`
	IsEncrypted   bool                   `protobuf:"varint,12,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	DecryptFailed bool                   `protobuf:"varint,13,opt,name=decrypt_failed,json=decryptFailed,proto3" json:"decrypt_failed,omitempty"`
	Attachments   []*FileRef             `protobuf:"bytes,14,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Reactions     []*Reaction            `protobuf:"bytes,15,rep,name=reactions,proto3" json:"reactions,omitempty"`
	IsPinned      bool                   `protobuf:"varint,16,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	Platform      string                 `protobuf:"bytes,17,opt,name=platform,proto3" json:"platform,omitempty"`
	ExtraJson     []byte                 `protobuf:"bytes,18,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"` // platform-specific JSON blob
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Message) GetEditedAtMs() int64 {
	if x != nil {
		return x.EditedAtMs
	}
	return 0
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *Message) GetReplyToId() string {
	if x != nil {
		return x.ReplyToId
	}
	return ""
}

func (x *Message) GetReplyPreview() string {
	if x != nil {
		return x.ReplyPreview
	}
	return ""
}

func (x *Message) GetForwardFrom() string {
	if x != nil {
		return x.ForwardFrom
	}
	return ""
}

func (x *Message) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

func (x *Message) GetDecryptFailed() bool {
	if x != nil {
		return x.DecryptFailed
	}
	return false
}

func (x *Message) GetAttachments() []*FileRef {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Message) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *Message) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *Message) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Message) GetExtraJson() []byte {
	if x != nil {
		return x.ExtraJson
	}
	return nil
}

type OutgoingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ReplyToId     string                 `protobuf:"bytes,2,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"`
	Attachments   []*FileRef             `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ExtraJson     []byte                 `protobuf:"bytes,4,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingMessage) Reset() {
	*x = OutgoingMessage{}
	mi := &file_proto_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingMessage) ProtoMessage() {}

func (x *OutgoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingMessage.ProtoReflect.Descriptor instead.
func (*OutgoingMessage) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{5}
}

func (x *OutgoingMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OutgoingMessage) GetReplyToId() string {
	if x != nil {
		return x.ReplyToId
	}
	return ""
}

func (x *OutgoingMessage) GetAttachments() []*FileRef {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *OutgoingMessage) GetExtraJson() []byte {
	if x != nil {
		return x.ExtraJson
	}
	return nil
}

type FileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ThumbB64      string                 `protobuf:"bytes,6,opt,name=thumb_b64,json=thumbB64,proto3" json:"thumb_b64,omitempty"`
	Extra         string                 `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_proto_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{6}
}

func (x *FileRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileRef) GetThumbB64() string {
	if x != nil {
		return x.ThumbB64
	}
	return ""
}

func (x *FileRef) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // local path — replaces io.Reader
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_proto_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{7}
}

func (x *FileUploadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileUploadRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type Reaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emoji         string                 `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ByMe          bool                   `protobuf:"varint,3,opt,name=by_me,json=byMe,proto3" json:"by_me,omitempty"`
	PeerId        string                 `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerName      string                 `protobuf:"bytes,5,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_proto_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{8}
}

func (x *Reaction) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *Reaction) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Reaction) GetByMe() bool {
	if x != nil {
		return x.ByMe
	}
	return false
}

func (x *Reaction) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Reaction) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

type ReadState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MyLastRead    string                 `protobuf:"bytes,1,opt,name=my_last_read,json=myLastRead,proto3" json:"my_last_read,omitempty"`
	PeerLastRead  map[string]string      `protobuf:"bytes,2,rep,name=peer_last_read,json=peerLastRead,proto3" json:"peer_last_read,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadState) Reset() {
	*x = ReadState{}
	mi := &file_proto_models_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadState) ProtoMessage() {}

func (x *ReadState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadState.ProtoReflect.Descriptor instead.
func (*ReadState) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{9}
}

func (x *ReadState) GetMyLastRead() string {
	if x != nil {
		return x.MyLastRead
	}
	return ""
}

func (x *ReadState) GetPeerLastRead() map[string]string {
	if x != nil {
		return x.PeerLastRead
	}
	return nil
}

type CallSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	IsVideo       bool                   `protobuf:"varint,3,opt,name=is_video,json=isVideo,proto3" json:"is_video,omitempty"`
	IsGroup       bool                   `protobuf:"varint,4,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	Participants  []*CallParticipant     `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	State         CallState              `protobuf:"varint,6,opt,name=state,proto3,enum=uniclient.CallState" json:"state,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallSession) Reset() {
	*x = CallSession{}
	mi := &file_proto_models_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSession) ProtoMessage() {}

func (x *CallSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSession.ProtoReflect.Descriptor instead.
func (*CallSession) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{10}
}

func (x *CallSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallSession) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CallSession) GetIsVideo() bool {
	if x != nil {
		return x.IsVideo
	}
	return false
}

func (x *CallSession) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *CallSession) GetParticipants() []*CallParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *CallSession) GetState() CallState {
	if x != nil {
		return x.State
	}
	return CallState_CALL_STATE_UNSPECIFIED
}

func (x *CallSession) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CallParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsMuted       bool                   `protobuf:"varint,3,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsSpeaking    bool                   `protobuf:"varint,4,opt,name=is_speaking,json=isSpeaking,proto3" json:"is_speaking,omitempty"`
	HasVideo      bool                   `protobuf:"varint,5,opt,name=has_video,json=hasVideo,proto3" json:"has_video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallParticipant) Reset() {
	*x = CallParticipant{}
	mi := &file_proto_models_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallParticipant) ProtoMessage() {}

func (x *CallParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallParticipant.ProtoReflect.Descriptor instead.
func (*CallParticipant) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{11}
}

func (x *CallParticipant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CallParticipant) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CallParticipant) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *CallParticipant) GetIsSpeaking() bool {
	if x != nil {
		return x.IsSpeaking
	}
	return false
}

func (x *CallParticipant) GetHasVideo() bool {
	if x != nil {
		return x.HasVideo
	}
	return false
}

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChatIds       []string               `protobuf:"bytes,3,rep,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_proto_models_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{12}
}

func (x *Folder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Folder) GetChatIds() []string {
	if x != nil {
		return x.ChatIds
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	AppName       string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppVersion    string                 `protobuf:"bytes,5,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Ip            string                 `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	LastActiveMs  int64                  `protobuf:"varint,8,opt,name=last_active_ms,json=lastActiveMs,proto3" json:"last_active_ms,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,9,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_models_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{13}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Session) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Session) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Session) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Session) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Session) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Session) GetLastActiveMs() int64 {
	if x != nil {
		return x.LastActiveMs
	}
	return 0
}

func (x *Session) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

type VerificationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	FromUser      string                 `protobuf:"bytes,3,opt,name=from_user,json=fromUser,proto3" json:"from_user,omitempty"`
	FromDevice    string                 `protobuf:"bytes,4,opt,name=from_device,json=fromDevice,proto3" json:"from_device,omitempty"`
	Emojis        []string               `protobuf:"bytes,5,rep,name=emojis,proto3" json:"emojis,omitempty"`
	EmojiSymbols  []string               `protobuf:"bytes,6,rep,name=emoji_symbols,json=emojiSymbols,proto3" json:"emoji_symbols,omitempty"`
	Decimals      []int32                `protobuf:"varint,7,rep,packed,name=decimals,proto3" json:"decimals,omitempty"`
	CancelCode    string                 `protobuf:"bytes,8,opt,name=cancel_code,json=cancelCode,proto3" json:"cancel_code,omitempty"`
	CancelReason  string                 `protobuf:"bytes,9,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationInfo) Reset() {
	*x = VerificationInfo{}
	mi := &file_proto_models_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationInfo) ProtoMessage() {}

func (x *VerificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationInfo.ProtoReflect.Descriptor instead.
func (*VerificationInfo) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{14}
}

func (x *VerificationInfo) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerificationInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *VerificationInfo) GetFromUser() string {
	if x != nil {
		return x.FromUser
	}
	return ""
}

func (x *VerificationInfo) GetFromDevice() string {
	if x != nil {
		return x.FromDevice
	}
	return ""
}

func (x *VerificationInfo) GetEmojis() []string {
	if x != nil {
		return x.Emojis
	}
	return nil
}

func (x *VerificationInfo) GetEmojiSymbols() []string {
	if x != nil {
		return x.EmojiSymbols
	}
	return nil
}

func (x *VerificationInfo) GetDecimals() []int32 {
	if x != nil {
		return x.Decimals
	}
	return nil
}

func (x *VerificationInfo) GetCancelCode() string {
	if x != nil {
		return x.CancelCode
	}
	return ""
}

func (x *VerificationInfo) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UpdateType             `protobuf:"varint,1,opt,name=type,proto3,enum=uniclient.UpdateType" json:"type,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Message       *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReadState     *ReadState             `protobuf:"bytes,6,opt,name=read_state,json=readState,proto3" json:"read_state,omitempty"`
	Call          *CallSession           `protobuf:"bytes,7,opt,name=call,proto3" json:"call,omitempty"`
	IsOnline      bool                   `protobuf:"varint,8,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	HasIsOnline   bool                   `protobuf:"varint,9,opt,name=has_is_online,json=hasIsOnline,proto3" json:"has_is_online,omitempty"` // distinguishes false from unset
	Verification  *VerificationInfo      `protobuf:"bytes,10,opt,name=verification,proto3" json:"verification,omitempty"`
	ConnState     string                 `protobuf:"bytes,11,opt,name=conn_state,json=connState,proto3" json:"conn_state,omitempty"`
	Platform      string                 `protobuf:"bytes,12,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_proto_models_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{15}
}

func (x *Update) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATE_TYPE_UNSPECIFIED
}

func (x *Update) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Update) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Update) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Update) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Update) GetReadState() *ReadState {
	if x != nil {
		return x.ReadState
	}
	return nil
}

func (x *Update) GetCall() *CallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *Update) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *Update) GetHasIsOnline() bool {
	if x != nil {
		return x.HasIsOnline
	}
	return false
}

func (x *Update) GetVerification() *VerificationInfo {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *Update) GetConnState() string {
	if x != nil {
		return x.ConnState
	}
	return ""
}

func (x *Update) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type BridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreId        string                 `protobuf:"bytes,1,opt,name=core_id,json=coreId,proto3" json:"core_id,omitempty"` // which core instance to call
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`               // fully-qualified method name (e.g. "SendMessage")
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`             // serialized per-method request proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeRequest) Reset() {
	*x = BridgeRequest{}
	mi := &file_proto_models_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeRequest) ProtoMessage() {}

func (x *BridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeRequest.ProtoReflect.Descriptor instead.
func (*BridgeRequest) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{16}
}

func (x *BridgeRequest) GetCoreId() string {
	if x != nil {
		return x.CoreId
	}
	return ""
}

func (x *BridgeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BridgeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // empty on success
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // sentinel category: "auth", "network", "not_found", etc.
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                      // serialized per-method response proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeResponse) Reset() {
	*x = BridgeResponse{}
	mi := &file_proto_models_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeResponse) ProtoMessage() {}

func (x *BridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeResponse.ProtoReflect.Descriptor instead.
func (*BridgeResponse) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{17}
}

func (x *BridgeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BridgeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BridgeResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BridgeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Event from Go → Dart (async updates)
type BridgeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreId        string                 `protobuf:"bytes,1,opt,name=core_id,json=coreId,proto3" json:"core_id,omitempty"`
	Update        *Update                `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`                              // core events (core_id != "__engine")
	EngineEvent   []byte                 `protobuf:"bytes,3,opt,name=engine_event,json=engineEvent,proto3" json:"engine_event,omitempty"` // engine events (core_id == "__engine"), JSON-encoded EngineEvent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeEvent) Reset() {
	*x = BridgeEvent{}
	mi := &file_proto_models_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeEvent) ProtoMessage() {}

func (x *BridgeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeEvent.ProtoReflect.Descriptor instead.
func (*BridgeEvent) Descriptor() ([]byte, []int) {
	return file_proto_models_proto_rawDescGZIP(), []int{18}
}

func (x *BridgeEvent) GetCoreId() string {
	if x != nil {
		return x.CoreId
	}
	return ""
}

func (x *BridgeEvent) GetUpdate() *Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *BridgeEvent) GetEngineEvent() []byte {
	if x != nil {
		return x.EngineEvent
	}
	return nil
}

var File_proto_models_proto protoreflect.FileDescriptor

const file_proto_models_proto_rawDesc = "" +
	"\n" +
	"\x12proto/models.proto\x12\tuniclient\"\x8d\x02\n" +
	"\n" +
	"AuthConfig\x12'\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x13.uniclient.AuthModeR\x04mode\x12\x1b\n" +
	"\tbot_token\x18\x02 \x01(\tR\bbotToken\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x10\n" +
	"\x03otp\x18\x04 \x01(\tR\x03otp\x12\x1f\n" +
	"\vpassword_2f\x18\x05 \x01(\tR\n" +
	"password2f\x126\n" +
	"\x05extra\x18\x06 \x03(\v2 .uniclient.AuthConfig.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x0ePaginationOpts\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\tR\x06offset\"\x9b\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"avatar_b64\x18\x06 \x01(\tR\tavatarB64\x12\x15\n" +
	"\x06is_bot\x18\a \x01(\bR\x05isBot\x12\x1b\n" +
	"\tis_online\x18\b \x01(\bR\bisOnline\x12 \n" +
	"\flast_seen_ms\x18\t \x01(\x03R\n" +
	"lastSeenMs\x12\x1a\n" +
	"\bplatform\x18\n" +
	" \x01(\tR\bplatform\"\xa4\x03\n" +
	"\x06Dialog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.uniclient.ChatTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"avatar_b64\x18\x05 \x01(\tR\tavatarB64\x125\n" +
	"\flast_message\x18\x06 \x01(\v2\x12.uniclient.MessageR\vlastMessage\x12!\n" +
	"\funread_count\x18\a \x01(\x05R\vunreadCount\x12\x19\n" +
	"\bis_muted\x18\b \x01(\bR\aisMuted\x12\x1b\n" +
	"\tis_pinned\x18\t \x01(\bR\bisPinned\x12\x1f\n" +
	"\vis_archived\x18\n" +
	" \x01(\bR\n" +
	"isArchived\x12!\n" +
	"\fmember_count\x18\v \x01(\x05R\vmemberCount\x12\x1b\n" +
	"\tparent_id\x18\f \x01(\tR\bparentId\x12\x1a\n" +
	"\bplatform\x18\r \x01(\tR\bplatform\"\xee\x04\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\x12 \n" +
	"\fedited_at_ms\x18\a \x01(\x03R\n" +
	"editedAtMs\x120\n" +
	"\x06status\x18\b \x01(\x0e2\x18.uniclient.MessageStatusR\x06status\x12\x1e\n" +
	"\vreply_to_id\x18\t \x01(\tR\treplyToId\x12#\n" +
	"\rreply_preview\x18\n" +
	" \x01(\tR\freplyPreview\x12!\n" +
	"\fforward_from\x18\v \x01(\tR\vforwardFrom\x12!\n" +
	"\fis_encrypted\x18\f \x01(\bR\visEncrypted\x12%\n" +
	"\x0edecrypt_failed\x18\r \x01(\bR\rdecryptFailed\x124\n" +
	"\vattachments\x18\x0e \x03(\v2\x12.uniclient.FileRefR\vattachments\x121\n" +
	"\treactions\x18\x0f \x03(\v2\x13.uniclient.ReactionR\treactions\x12\x1b\n" +
	"\tis_pinned\x18\x10 \x01(\bR\bisPinned\x12\x1a\n" +
	"\bplatform\x18\x11 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"extra_json\x18\x12 \x01(\fR\textraJson\"\x9a\x01\n" +
	"\x0fOutgoingMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\vreply_to_id\x18\x02 \x01(\tR\treplyToId\x124\n" +
	"\vattachments\x18\x03 \x03(\v2\x12.uniclient.FileRefR\vattachments\x12\x1d\n" +
	"\n" +
	"extra_json\x18\x04 \x01(\fR\textraJson\"\xa3\x01\n" +
	"\aFileRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1b\n" +
	"\tthumb_b64\x18\x06 \x01(\tR\bthumbB64\x12\x14\n" +
	"\x05extra\x18\a \x01(\tR\x05extra\"u\n" +
	"\x11FileUploadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\"\x81\x01\n" +
	"\bReaction\x12\x14\n" +
	"\x05emoji\x18\x01 \x01(\tR\x05emoji\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x13\n" +
	"\x05by_me\x18\x03 \x01(\bR\x04byMe\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tpeer_name\x18\x05 \x01(\tR\bpeerName\"\xbc\x01\n" +
	"\tReadState\x12 \n" +
	"\fmy_last_read\x18\x01 \x01(\tR\n" +
	"myLastRead\x12L\n" +
	"\x0epeer_last_read\x18\x02 \x03(\v2&.uniclient.ReadState.PeerLastReadEntryR\fpeerLastRead\x1a?\n" +
	"\x11PeerLastReadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x02\n" +
	"\vCallSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x19\n" +
	"\bis_video\x18\x03 \x01(\bR\aisVideo\x12\x19\n" +
	"\bis_group\x18\x04 \x01(\bR\aisGroup\x12>\n" +
	"\fparticipants\x18\x05 \x03(\v2\x1a.uniclient.CallParticipantR\fparticipants\x12*\n" +
	"\x05state\x18\x06 \x01(\x0e2\x14.uniclient.CallStateR\x05state\x124\n" +
	"\x04meta\x18\a \x03(\v2 .uniclient.CallSession.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\x0fCallParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bis_muted\x18\x03 \x01(\bR\aisMuted\x12\x1f\n" +
	"\vis_speaking\x18\x04 \x01(\bR\n" +
	"isSpeaking\x12\x1b\n" +
	"\thas_video\x18\x05 \x01(\bR\bhasVideo\"G\n" +
	"\x06Folder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bchat_ids\x18\x03 \x03(\tR\achatIds\"\xfa\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12\x1f\n" +
	"\vapp_version\x18\x05 \x01(\tR\n" +
	"appVersion\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12$\n" +
	"\x0elast_active_ms\x18\b \x01(\x03R\flastActiveMs\x12\x1d\n" +
	"\n" +
	"is_current\x18\t \x01(\bR\tisCurrent\"\xac\x02\n" +
	"\x10VerificationInfo\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1b\n" +
	"\tfrom_user\x18\x03 \x01(\tR\bfromUser\x12\x1f\n" +
	"\vfrom_device\x18\x04 \x01(\tR\n" +
	"fromDevice\x12\x16\n" +
	"\x06emojis\x18\x05 \x03(\tR\x06emojis\x12#\n" +
	"\remoji_symbols\x18\x06 \x03(\tR\femojiSymbols\x12\x1a\n" +
	"\bdecimals\x18\a \x03(\x05R\bdecimals\x12\x1f\n" +
	"\vcancel_code\x18\b \x01(\tR\n" +
	"cancelCode\x12#\n" +
	"\rcancel_reason\x18\t \x01(\tR\fcancelReason\"\xd0\x03\n" +
	"\x06Update\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.uniclient.UpdateTypeR\x04type\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12,\n" +
	"\amessage\x18\x03 \x01(\v2\x12.uniclient.MessageR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x123\n" +
	"\n" +
	"read_state\x18\x06 \x01(\v2\x14.uniclient.ReadStateR\treadState\x12*\n" +
	"\x04call\x18\a \x01(\v2\x16.uniclient.CallSessionR\x04call\x12\x1b\n" +
	"\tis_online\x18\b \x01(\bR\bisOnline\x12\"\n" +
	"\rhas_is_online\x18\t \x01(\bR\vhasIsOnline\x12?\n" +
	"\fverification\x18\n" +
	" \x01(\v2\x1b.uniclient.VerificationInfoR\fverification\x12\x1d\n" +
	"\n" +
	"conn_state\x18\v \x01(\tR\tconnState\x12\x1a\n" +
	"\bplatform\x18\f \x01(\tR\bplatform\"Z\n" +
	"\rBridgeRequest\x12\x17\n" +
	"\acore_id\x18\x01 \x01(\tR\x06coreId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"o\n" +
	"\x0eBridgeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"t\n" +
	"\vBridgeEvent\x12\x17\n" +
	"\acore_id\x18\x01 \x01(\tR\x06coreId\x12)\n" +
	"\x06update\x18\x02 \x01(\v2\x11.uniclient.UpdateR\x06update\x12!\n" +
	"\fengine_event\x18\x03 \x01(\fR\vengineEvent*x\n" +
	"\bChatType\x12\x19\n" +
	"\x15CHAT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCHAT_TYPE_DM\x10\x01\x12\x13\n" +
	"\x0fCHAT_TYPE_GROUP\x10\x02\x12\x15\n" +
	"\x11CHAT_TYPE_CHANNEL\x10\x03\x12\x13\n" +
	"\x0fCHAT_TYPE_TOPIC\x10\x04*\xb6\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_SENDING\x10\x01\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x02\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x03\x12\x17\n" +
	"\x13MESSAGE_STATUS_READ\x10\x04\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x05*\xcc\x02\n" +
	"\n" +
	"UpdateType\x12\x1b\n" +
	"\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17UPDATE_TYPE_NEW_MESSAGE\x10\x01\x12\x1c\n" +
	"\x18UPDATE_TYPE_EDIT_MESSAGE\x10\x02\x12\x1e\n" +
	"\x1aUPDATE_TYPE_DELETE_MESSAGE\x10\x03\x12\x1a\n" +
	"\x16UPDATE_TYPE_READ_STATE\x10\x04\x12\x1b\n" +
	"\x17UPDATE_TYPE_USER_STATUS\x10\x05\x12\x16\n" +
	"\x12UPDATE_TYPE_TYPING\x10\x06\x12\x1a\n" +
	"\x16UPDATE_TYPE_CALL_STATE\x10\a\x12\x1d\n" +
	"\x19UPDATE_TYPE_GROUP_MEMBERS\x10\b\x12\x1c\n" +
	"\x18UPDATE_TYPE_VERIFICATION\x10\t\x12\x1c\n" +
	"\x18UPDATE_TYPE_CONNECTIVITY\x10\n" +
	"*\x87\x01\n" +
	"\tCallState\x12\x1a\n" +
	"\x16CALL_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CALL_STATE_RINGING\x10\x01\x12\x19\n" +
	"\x15CALL_STATE_CONNECTING\x10\x02\x12\x15\n" +
	"\x11CALL_STATE_ACTIVE\x10\x03\x12\x14\n" +
	"\x10CALL_STATE_ENDED\x10\x04*L\n" +
	"\bAuthMode\x12\x19\n" +
	"\x15AUTH_MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rAUTH_MODE_BOT\x10\x01\x12\x12\n" +
	"\x0eAUTH_MODE_USER\x10\x02B\x11Z\x0funiclient/protob\x06proto3"

var (
	file_proto_models_proto_rawDescOnce sync.Once
	file_proto_models_proto_rawDescData []byte
)

func file_proto_models_proto_rawDescGZIP() []byte {
	file_proto_models_proto_rawDescOnce.Do(func() {
		file_proto_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_models_proto_rawDesc), len(file_proto_models_proto_rawDesc)))
	})
	return file_proto_models_proto_rawDescData
}

var file_proto_models_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_models_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_models_proto_goTypes = []any{
	(ChatType)(0),             // 0: uniclient.ChatType
	(MessageStatus)(0),        // 1: uniclient.MessageStatus
	(UpdateType)(0),           // 2: uniclient.UpdateType
	(CallState)(0),            // 3: uniclient.CallState
	(AuthMode)(0),             // 4: uniclient.AuthMode
	(*AuthConfig)(nil),        // 5: uniclient.AuthConfig
	(*PaginationOpts)(nil),    // 6: uniclient.PaginationOpts
	(*User)(nil),              // 7: uniclient.User
	(*Dialog)(nil),            // 8: uniclient.Dialog
	(*Message)(nil),           // 9: uniclient.Message
	(*OutgoingMessage)(nil),   // 10: uniclient.OutgoingMessage
	(*FileRef)(nil),           // 11: uniclient.FileRef
	(*FileUploadRequest)(nil), // 12: uniclient.FileUploadRequest
	(*Reaction)(nil),          // 13: uniclient.Reaction
	(*ReadState)(nil),         // 14: uniclient.ReadState
	(*CallSession)(nil),       // 15: uniclient.CallSession
	(*CallParticipant)(nil),   // 16: uniclient.CallParticipant
	(*Folder)(nil),            // 17: uniclient.Folder
	(*Session)(nil),           // 18: uniclient.Session
	(*VerificationInfo)(nil),  // 19: uniclient.VerificationInfo
	(*Update)(nil),            // 20: uniclient.Update
	(*BridgeRequest)(nil),     // 21: uniclient.BridgeRequest
	(*BridgeResponse)(nil),    // 22: uniclient.BridgeResponse
	(*BridgeEvent)(nil),       // 23: uniclient.BridgeEvent
	nil,                       // 24: uniclient.AuthConfig.ExtraEntry
	nil,                       // 25: uniclient.ReadState.PeerLastReadEntry
	nil,                       // 26: uniclient.CallSession.MetaEntry
}
var file_proto_models_proto_depIdxs = []int32{
	4,  // 0: uniclient.AuthConfig.mode:type_name -> uniclient.AuthMode
	24, // 1: uniclient.AuthConfig.extra:type_name -> uniclient.AuthConfig.ExtraEntry
	0,  // 2: uniclient.Dialog.type:type_name -> uniclient.ChatType
	9,  // 3: uniclient.Dialog.last_message:type_name -> uniclient.Message
	1,  // 4: uniclient.Message.status:type_name -> uniclient.MessageStatus
	11, // 5: uniclient.Message.attachments:type_name -> uniclient.FileRef
	13, // 6: uniclient.Message.reactions:type_name -> uniclient.Reaction
	11, // 7: uniclient.OutgoingMessage.attachments:type_name -> uniclient.FileRef
	25, // 8: uniclient.ReadState.peer_last_read:type_name -> uniclient.ReadState.PeerLastReadEntry
	16, // 9: uniclient.CallSession.participants:type_name -> uniclient.CallParticipant
	3,  // 10: uniclient.CallSession.state:type_name -> uniclient.CallState
	26, // 11: uniclient.CallSession.meta:type_name -> uniclient.CallSession.MetaEntry
	2,  // 12: uniclient.Update.type:type_name -> uniclient.UpdateType
	9,  // 13: uniclient.Update.message:type_name -> uniclient.Message
	14, // 14: uniclient.Update.read_state:type_name -> uniclient.ReadState
	15, // 15: uniclient.Update.call:type_name -> uniclient.CallSession
	19, // 16: uniclient.Update.verification:type_name -> uniclient.VerificationInfo
	20, // 17: uniclient.BridgeEvent.update:type_name -> uniclient.Update
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_models_proto_init() }
func file_proto_models_proto_init() {
	if File_proto_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_models_proto_rawDesc), len(file_proto_models_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_models_proto_goTypes,
		DependencyIndexes: file_proto_models_proto_depIdxs,
		EnumInfos:         file_proto_models_proto_enumTypes,
		MessageInfos:      file_proto_models_proto_msgTypes,
	}.Build()
	File_proto_models_proto = out.File
	file_proto_models_proto_goTypes = nil
	file_proto_models_proto_depIdxs = nil
}
