syntax = "proto3";

package uniclient.github;

option go_package = "uniclient/proto/cores";

import "proto/models.proto";

message GithubAcceptCallRequest {
  string call_id = 1;
}

message GithubAcceptCallResponse {
  uniclient.CallSession result_1 = 1;
}

message GithubAcceptInvitationRequest {
  int64 invitation_id = 1;
}

message GithubAcceptInvitationResponse {
}

message GithubAddCollaboratorRequest {
  string owner = 1;
  string repo = 2;
  string username = 3;
  bytes payload = 4;
}

message GithubAddCollaboratorResponse {
  bytes result_1 = 1;
}

message GithubAddContactRequest {
  string param_1 = 1;
  string first_name = 2;
  string param_3 = 3;
}

message GithubAddContactResponse {
}

message GithubAddDiscussionCommentRequest {
  string discussion_id = 1;
  string body = 2;
}

message GithubAddDiscussionCommentResponse {
  bytes result_1 = 1;
}

message GithubAddEmailRequest {
  repeated string emails = 1;
}

message GithubAddEmailResponse {
  bytes result_1 = 1;
}

message GithubAddIssueAssigneesRequest {
  string owner = 1;
  string repo = 2;
  int64 issue_number = 3;
  bytes payload = 4;
}

message GithubAddIssueAssigneesResponse {
  bytes result_1 = 1;
}

message GithubAddLabelsToIssueRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  repeated string labels = 4;
}

message GithubAddLabelsToIssueResponse {
  bytes result_1 = 1;
}

message GithubAddMembersRequest {
  string chat_id = 1;
  repeated string user_ids = 2;
}

message GithubAddMembersResponse {
}

message GithubAddProjectV2ItemRequest {
  string project_id = 1;
  string content_id = 2;
}

message GithubAddProjectV2ItemResponse {
  bytes result_1 = 1;
}

message GithubAddSocialAccountRequest {
  repeated string account_urls = 1;
}

message GithubAddSocialAccountResponse {
  bytes result_1 = 1;
}

message GithubAddSubIssueRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  int64 sub_issue_id = 4;
}

message GithubAddSubIssueResponse {
  bytes result_1 = 1;
}

message GithubAddTeamMemberRequest {
  string org = 1;
  string team_slug = 2;
  string username = 3;
  string role = 4;
}

message GithubAddTeamMemberResponse {
  bytes result_1 = 1;
}

message GithubAddTeamRepoRequest {
  string org = 1;
  string team_slug = 2;
  string owner = 3;
  string repo = 4;
  bytes payload = 5;
}

message GithubAddTeamRepoResponse {
  bytes result_1 = 1;
}

message GithubArchiveChatRequest {
  string chat_id = 1;
  bool archived = 2;
}

message GithubArchiveChatResponse {
}

message GithubAssignTeamRoleRequest {
  string org = 1;
  string team_slug = 2;
  int64 role_id = 3;
}

message GithubAssignTeamRoleResponse {
  bytes result_1 = 1;
}

message GithubAssignUserRoleRequest {
  string org = 1;
  string username = 2;
  int64 role_id = 3;
}

message GithubAssignUserRoleResponse {
  bytes result_1 = 1;
}

message GithubAuthenticateRequest {
  uniclient.AuthConfig cfg = 1;
}

message GithubAuthenticateResponse {
}

message GithubBanMemberRequest {
  string chat_id = 1;
  string user_id = 2;
}

message GithubBanMemberResponse {
}

message GithubBlockOrgUserRequest {
  string org = 1;
  string username = 2;
}

message GithubBlockOrgUserResponse {
  bytes result_1 = 1;
}

message GithubBlockUserRequest {
  string user_id = 1;
}

message GithubBlockUserResponse {
}

message GithubCancelOrgInvitationRequest {
  string org = 1;
  int64 invitation_id = 2;
}

message GithubCancelOrgInvitationResponse {
}

message GithubCapabilitiesRequest {
}

message GithubCapabilitiesResponse {
  repeated string result_1 = 1;
}

message GithubCheckRateLimitRequest {
}

message GithubCheckRateLimitResponse {
  bytes result_1 = 1;
}

message GithubCloseRequest {
}

message GithubCloseResponse {
}

message GithubConvertToOutsideCollaboratorRequest {
  string org = 1;
  string username = 2;
}

message GithubConvertToOutsideCollaboratorResponse {
  bytes result_1 = 1;
}

message GithubCopyProjectV2Request {
  string project_id = 1;
  string owner_id = 2;
  string title = 3;
}

message GithubCopyProjectV2Response {
  bytes result_1 = 1;
}

message GithubCreateChannelRequest {
  string name = 1;
  string description = 2;
}

message GithubCreateChannelResponse {
  uniclient.Dialog result_1 = 1;
}

message GithubCreateCommitCommentRequest {
  string owner = 1;
  string repo = 2;
  string sha = 3;
  string body = 4;
}

message GithubCreateCommitCommentResponse {
  bytes result_1 = 1;
}

message GithubCreateCommitCommentReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
  bytes payload = 4;
}

message GithubCreateCommitCommentReactionResponse {
  bytes result_1 = 1;
}

message GithubCreateDiscussionRequest {
  string repo_id = 1;
  string category_id = 2;
  string title = 3;
  string body = 4;
}

message GithubCreateDiscussionResponse {
  bytes result_1 = 1;
}

message GithubCreateFolderRequest {
  string name = 1;
  repeated string chat_ids = 2;
}

message GithubCreateFolderResponse {
  uniclient.Folder result_1 = 1;
}

message GithubCreateGistRequest {
  string description = 1;
  bytes files = 2;
  bool public = 3;
}

message GithubCreateGistResponse {
  bytes result_1 = 1;
}

message GithubCreateGistCommentRequest {
  string gist_id = 1;
  string body = 2;
}

message GithubCreateGistCommentResponse {
  bytes result_1 = 1;
}

message GithubCreateGroupRequest {
  string name = 1;
  repeated string members = 2;
}

message GithubCreateGroupResponse {
  uniclient.Dialog result_1 = 1;
}

message GithubCreateIssueCommentReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
  bytes payload = 4;
}

message GithubCreateIssueCommentReactionResponse {
  bytes result_1 = 1;
}

message GithubCreateIssueReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 issue_number = 3;
  bytes payload = 4;
}

message GithubCreateIssueReactionResponse {
  bytes result_1 = 1;
}

message GithubCreateLabelRequest {
  string owner = 1;
  string repo = 2;
  string name = 3;
  string color = 4;
  string description = 5;
}

message GithubCreateLabelResponse {
  bytes result_1 = 1;
}

message GithubCreateMilestoneRequest {
  string owner = 1;
  string repo = 2;
  string title = 3;
  string description = 4;
}

message GithubCreateMilestoneResponse {
  bytes result_1 = 1;
}

message GithubCreateOrgInvitationRequest {
  string org = 1;
  bytes payload = 2;
}

message GithubCreateOrgInvitationResponse {
  bytes result_1 = 1;
}

message GithubCreatePRCommentRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  string body = 4;
  string path = 5;
  string commit_id = 6;
  int64 line = 7;
}

message GithubCreatePRCommentResponse {
  bytes result_1 = 1;
}

message GithubCreatePRCommentReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
  bytes payload = 4;
}

message GithubCreatePRCommentReactionResponse {
  bytes result_1 = 1;
}

message GithubCreatePRCommentReplyRequest {
  string owner = 1;
  string repo = 2;
  int64 pr_number = 3;
  int64 comment_id = 4;
  bytes payload = 5;
}

message GithubCreatePRCommentReplyResponse {
  bytes result_1 = 1;
}

message GithubCreatePRReviewRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  string body = 4;
  string event = 5;
}

message GithubCreatePRReviewResponse {
  bytes result_1 = 1;
}

message GithubCreatePollRequest {
  string chat_id = 1;
  string question = 2;
  repeated string options = 3;
}

message GithubCreatePollResponse {
  uniclient.Message result_1 = 1;
}

message GithubCreateProjectV2DraftItemRequest {
  string project_id = 1;
  bytes payload = 2;
}

message GithubCreateProjectV2DraftItemResponse {
  bytes result_1 = 1;
}

message GithubCreateProjectV2ViewRequest {
  string project_id = 1;
  bytes payload = 2;
}

message GithubCreateProjectV2ViewResponse {
  bytes result_1 = 1;
}

message GithubCreatePullRequestRequest {
  string owner = 1;
  string repo = 2;
  string title = 3;
  string head = 4;
  string base = 5;
  string body = 6;
}

message GithubCreatePullRequestResponse {
  bytes result_1 = 1;
}

message GithubCreateReleaseRequest {
  string owner = 1;
  string repo = 2;
  string tag_name = 3;
  string name = 4;
  string body = 5;
  bool draft = 6;
  bool prerelease = 7;
}

message GithubCreateReleaseResponse {
  bytes result_1 = 1;
}

message GithubCreateReleaseReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 release_id = 3;
  bytes payload = 4;
}

message GithubCreateReleaseReactionResponse {
  bytes result_1 = 1;
}

message GithubCreateTeamRequest {
  string org = 1;
  string name = 2;
  string description = 3;
  string privacy = 4;
}

message GithubCreateTeamResponse {
  bytes result_1 = 1;
}

message GithubCreateTopicRequest {
  string chat_id = 1;
  string name = 2;
}

message GithubCreateTopicResponse {
  uniclient.Dialog result_1 = 1;
}

message GithubDeclineCallRequest {
  string call_id = 1;
}

message GithubDeclineCallResponse {
}

message GithubDeclineInvitationRequest {
  int64 invitation_id = 1;
}

message GithubDeclineInvitationResponse {
}

message GithubDeleteCommitCommentRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
}

message GithubDeleteCommitCommentResponse {
}

message GithubDeleteCommitCommentReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
  int64 reaction_id = 4;
}

message GithubDeleteCommitCommentReactionResponse {
}

message GithubDeleteContactRequest {
  string user_id = 1;
}

message GithubDeleteContactResponse {
}

message GithubDeleteDiscussionRequest {
  string discussion_id = 1;
}

message GithubDeleteDiscussionResponse {
  bytes result_1 = 1;
}

message GithubDeleteDiscussionCommentRequest {
  string comment_id = 1;
}

message GithubDeleteDiscussionCommentResponse {
  bytes result_1 = 1;
}

message GithubDeleteEmailRequest {
  repeated string emails = 1;
}

message GithubDeleteEmailResponse {
}

message GithubDeleteGistRequest {
  string gist_id = 1;
}

message GithubDeleteGistResponse {
}

message GithubDeleteInvitationRequest {
  string owner = 1;
  string repo = 2;
  int64 invitation_id = 3;
}

message GithubDeleteInvitationResponse {
}

message GithubDeleteIssueCommentReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
  int64 reaction_id = 4;
}

message GithubDeleteIssueCommentReactionResponse {
}

message GithubDeleteIssueReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 issue_number = 3;
  int64 reaction_id = 4;
}

message GithubDeleteIssueReactionResponse {
}

message GithubDeleteLabelRequest {
  string owner = 1;
  string repo = 2;
  string name = 3;
}

message GithubDeleteLabelResponse {
}

message GithubDeleteMessageRequest {
  string chat_id = 1;
  string msg_id = 2;
}

message GithubDeleteMessageResponse {
}

message GithubDeleteMilestoneRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
}

message GithubDeleteMilestoneResponse {
}

message GithubDeletePRCommentReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
  int64 reaction_id = 4;
}

message GithubDeletePRCommentReactionResponse {
}

message GithubDeleteProjectV2Request {
  string project_id = 1;
}

message GithubDeleteProjectV2Response {
  bytes result_1 = 1;
}

message GithubDeleteProjectV2ItemRequest {
  string project_id = 1;
  string item_id = 2;
}

message GithubDeleteProjectV2ItemResponse {
  bytes result_1 = 1;
}

message GithubDeleteReleaseRequest {
  string owner = 1;
  string repo = 2;
  int64 release_id = 3;
}

message GithubDeleteReleaseResponse {
}

message GithubDeleteReleaseReactionRequest {
  string owner = 1;
  string repo = 2;
  int64 release_id = 3;
  int64 reaction_id = 4;
}

message GithubDeleteReleaseReactionResponse {
}

message GithubDeleteRepoRequest {
  string owner = 1;
  string repo = 2;
}

message GithubDeleteRepoResponse {
}

message GithubDeleteSocialAccountRequest {
  repeated string account_urls = 1;
}

message GithubDeleteSocialAccountResponse {
}

message GithubDeleteTeamRequest {
  string org = 1;
  string team_slug = 2;
}

message GithubDeleteTeamResponse {
}

message GithubDismissPRReviewRequest {
  string owner = 1;
  string repo = 2;
  int64 pr_number = 3;
  int64 review_id = 4;
  string message = 5;
}

message GithubDismissPRReviewResponse {
  bytes result_1 = 1;
}

message GithubEditChatDescriptionRequest {
  string chat_id = 1;
  string description = 2;
}

message GithubEditChatDescriptionResponse {
}

message GithubEditChatTitleRequest {
  string chat_id = 1;
  string title = 2;
}

message GithubEditChatTitleResponse {
}

message GithubEditMessageRequest {
  string chat_id = 1;
  string msg_id = 2;
  string text = 3;
}

message GithubEditMessageResponse {
  uniclient.Message result_1 = 1;
}

message GithubEndCallRequest {
  string param_1 = 1;
}

message GithubEndCallResponse {
}

message GithubForkRepoRequest {
  string owner = 1;
  string repo = 2;
}

message GithubForkRepoResponse {
  bytes result_1 = 1;
}

message GithubForwardMessageRequest {
  string from_chat_id = 1;
  string msg_id = 2;
  string to_chat_id = 3;
}

message GithubForwardMessageResponse {
  uniclient.Message result_1 = 1;
}

message GithubGetBlockedUsersRequest {
}

message GithubGetBlockedUsersResponse {
  repeated uniclient.User result_1 = 1;
}

message GithubGetChatInfoRequest {
  string chat_id = 1;
}

message GithubGetChatInfoResponse {
  uniclient.Dialog result_1 = 1;
}

message GithubGetContactsRequest {
}

message GithubGetContactsResponse {
  repeated uniclient.User result_1 = 1;
}

message GithubGetDialogsRequest {
  uniclient.PaginationOpts opts = 1;
}

message GithubGetDialogsResponse {
  repeated uniclient.Dialog result_1 = 1;
}

message GithubGetFeedsRequest {
}

message GithubGetFeedsResponse {
  bytes result_1 = 1;
}

message GithubGetFoldersRequest {
}

message GithubGetFoldersResponse {
  repeated uniclient.Folder result_1 = 1;
}

message GithubGetInviteLinkRequest {
  string chat_id = 1;
}

message GithubGetInviteLinkResponse {
  string result_1 = 1;
}

message GithubGetIssueEventRequest {
  string owner = 1;
  string repo = 2;
  int64 event_id = 3;
}

message GithubGetIssueEventResponse {
  bytes result_1 = 1;
}

message GithubGetIssueTimelineRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
}

message GithubGetIssueTimelineResponse {
  bytes result_1 = 1;
}

message GithubGetMembersRequest {
  string chat_id = 1;
  uniclient.PaginationOpts opts = 2;
}

message GithubGetMembersResponse {
  repeated uniclient.User result_1 = 1;
}

message GithubGetMessagesRequest {
  string chat_id = 1;
  uniclient.PaginationOpts opts = 2;
}

message GithubGetMessagesResponse {
  repeated uniclient.Message result_1 = 1;
}

message GithubGetNotificationThreadRequest {
  string thread_id = 1;
}

message GithubGetNotificationThreadResponse {
  bytes result_1 = 1;
}

message GithubGetOrgRequest {
  string org = 1;
}

message GithubGetOrgResponse {
  bytes result_1 = 1;
}

message GithubGetOrgInteractionLimitsRequest {
  string org = 1;
}

message GithubGetOrgInteractionLimitsResponse {
  bytes result_1 = 1;
}

message GithubGetOrgMembershipRequest {
  string org = 1;
  string username = 2;
}

message GithubGetOrgMembershipResponse {
  bytes result_1 = 1;
}

message GithubGetOrgRoleRequest {
  string org = 1;
  int64 role_id = 2;
}

message GithubGetOrgRoleResponse {
  bytes result_1 = 1;
}

message GithubGetProfileRequest {
  string user_id = 1;
}

message GithubGetProfileResponse {
  uniclient.User result_1 = 1;
}

message GithubGetProjectV2Request {
  string project_id = 1;
}

message GithubGetProjectV2Response {
  bytes result_1 = 1;
}

message GithubGetPullRequestRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
}

message GithubGetPullRequestResponse {
  bytes result_1 = 1;
}

message GithubGetReadStateRequest {
  string chat_id = 1;
}

message GithubGetReadStateResponse {
  uniclient.ReadState result_1 = 1;
}

message GithubGetRepoInteractionLimitsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubGetRepoInteractionLimitsResponse {
  bytes result_1 = 1;
}

message GithubGetRepoTopicsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubGetRepoTopicsResponse {
  bytes result_1 = 1;
}

message GithubGetRequestedReviewersRequest {
  string owner = 1;
  string repo = 2;
  int64 pr_number = 3;
}

message GithubGetRequestedReviewersResponse {
  bytes result_1 = 1;
}

message GithubGetSessionsRequest {
}

message GithubGetSessionsResponse {
  repeated uniclient.Session result_1 = 1;
}

message GithubGetUserHovercardRequest {
  string username = 1;
}

message GithubGetUserHovercardResponse {
  bytes result_1 = 1;
}

message GithubGetUserInteractionLimitsRequest {
}

message GithubGetUserInteractionLimitsResponse {
  bytes result_1 = 1;
}

message GithubGetUserOrgMembershipRequest {
  string org = 1;
}

message GithubGetUserOrgMembershipResponse {
  bytes result_1 = 1;
}

message GithubJoinGroupCallRequest {
  string param_1 = 1;
}

message GithubJoinGroupCallResponse {
  uniclient.CallSession result_1 = 1;
}

message GithubLeaveChatRequest {
  string chat_id = 1;
}

message GithubLeaveChatResponse {
}

message GithubListAuthenticatedUserIssuesRequest {
}

message GithubListAuthenticatedUserIssuesResponse {
  bytes result_1 = 1;
}

message GithubListCollaboratorsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListCollaboratorsResponse {
  bytes result_1 = 1;
}

message GithubListCommitCommentReactionsRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
}

message GithubListCommitCommentReactionsResponse {
  bytes result_1 = 1;
}

message GithubListCommitCommentsRequest {
  string owner = 1;
  string repo = 2;
  string sha = 3;
}

message GithubListCommitCommentsResponse {
  bytes result_1 = 1;
}

message GithubListContributorsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListContributorsResponse {
  bytes result_1 = 1;
}

message GithubListDiscussionsRequest {
  string owner = 1;
  string repo = 2;
  int64 first = 3;
}

message GithubListDiscussionsResponse {
  bytes result_1 = 1;
}

message GithubListEmailsRequest {
}

message GithubListEmailsResponse {
  bytes result_1 = 1;
}

message GithubListEventsRequest {
  int64 per_page = 1;
}

message GithubListEventsResponse {
  bytes result_1 = 1;
}

message GithubListFailedInvitationsRequest {
  string org = 1;
}

message GithubListFailedInvitationsResponse {
  bytes result_1 = 1;
}

message GithubListGistCommentsRequest {
  string gist_id = 1;
}

message GithubListGistCommentsResponse {
  bytes result_1 = 1;
}

message GithubListGistsRequest {
  int64 per_page = 1;
}

message GithubListGistsResponse {
  bytes result_1 = 1;
}

message GithubListInvitationTeamsRequest {
  string org = 1;
  int64 invitation_id = 2;
}

message GithubListInvitationTeamsResponse {
  bytes result_1 = 1;
}

message GithubListInvitationsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListInvitationsResponse {
  bytes result_1 = 1;
}

message GithubListIssueCommentReactionsRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
}

message GithubListIssueCommentReactionsResponse {
  bytes result_1 = 1;
}

message GithubListIssueEventsRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
}

message GithubListIssueEventsResponse {
  bytes result_1 = 1;
}

message GithubListIssueReactionsRequest {
  string owner = 1;
  string repo = 2;
  int64 issue_number = 3;
}

message GithubListIssueReactionsResponse {
  bytes result_1 = 1;
}

message GithubListLabelsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListLabelsResponse {
  bytes result_1 = 1;
}

message GithubListMilestonesRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListMilestonesResponse {
  bytes result_1 = 1;
}

message GithubListNotificationsRequest {
  bool all = 1;
  int64 per_page = 2;
}

message GithubListNotificationsResponse {
  bytes result_1 = 1;
}

message GithubListOrgBlockedUsersRequest {
  string org = 1;
}

message GithubListOrgBlockedUsersResponse {
  bytes result_1 = 1;
}

message GithubListOrgInvitationsRequest {
  string org = 1;
}

message GithubListOrgInvitationsResponse {
  bytes result_1 = 1;
}

message GithubListOrgIssuesRequest {
  string org = 1;
}

message GithubListOrgIssuesResponse {
  bytes result_1 = 1;
}

message GithubListOrgMembersRequest {
  string org = 1;
}

message GithubListOrgMembersResponse {
  bytes result_1 = 1;
}

message GithubListOrgProjectsV2Request {
  string org = 1;
}

message GithubListOrgProjectsV2Response {
  bytes result_1 = 1;
}

message GithubListOrgRolesRequest {
  string org = 1;
}

message GithubListOrgRolesResponse {
  bytes result_1 = 1;
}

message GithubListOrgTeamsRequest {
  string org = 1;
}

message GithubListOrgTeamsResponse {
  bytes result_1 = 1;
}

message GithubListOrgsRequest {
}

message GithubListOrgsResponse {
  bytes result_1 = 1;
}

message GithubListOutsideCollaboratorsRequest {
  string org = 1;
}

message GithubListOutsideCollaboratorsResponse {
  bytes result_1 = 1;
}

message GithubListPRCommentReactionsRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
}

message GithubListPRCommentReactionsResponse {
  bytes result_1 = 1;
}

message GithubListPRCommentsRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
}

message GithubListPRCommentsResponse {
  bytes result_1 = 1;
}

message GithubListPRReviewCommentsRequest {
  string owner = 1;
  string repo = 2;
  int64 pr_number = 3;
  int64 review_id = 4;
}

message GithubListPRReviewCommentsResponse {
  bytes result_1 = 1;
}

message GithubListPRReviewsRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
}

message GithubListPRReviewsResponse {
  bytes result_1 = 1;
}

message GithubListProjectV2FieldsRequest {
  string project_id = 1;
}

message GithubListProjectV2FieldsResponse {
  bytes result_1 = 1;
}

message GithubListProjectV2ItemsRequest {
  string project_id = 1;
}

message GithubListProjectV2ItemsResponse {
  bytes result_1 = 1;
}

message GithubListPublicMembersRequest {
  string org = 1;
}

message GithubListPublicMembersResponse {
  bytes result_1 = 1;
}

message GithubListPullRequestsRequest {
  string owner = 1;
  string repo = 2;
  string state = 3;
  int64 per_page = 4;
}

message GithubListPullRequestsResponse {
  bytes result_1 = 1;
}

message GithubListReleaseAssetsRequest {
  string owner = 1;
  string repo = 2;
  int64 release_id = 3;
}

message GithubListReleaseAssetsResponse {
  bytes result_1 = 1;
}

message GithubListReleaseReactionsRequest {
  string owner = 1;
  string repo = 2;
  int64 release_id = 3;
}

message GithubListReleaseReactionsResponse {
  bytes result_1 = 1;
}

message GithubListReleasesRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListReleasesResponse {
  bytes result_1 = 1;
}

message GithubListRepoEventsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListRepoEventsResponse {
  bytes result_1 = 1;
}

message GithubListRepoIssueEventsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListRepoIssueEventsResponse {
  bytes result_1 = 1;
}

message GithubListSocialAccountsRequest {
}

message GithubListSocialAccountsResponse {
  bytes result_1 = 1;
}

message GithubListStargazersRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListStargazersResponse {
  bytes result_1 = 1;
}

message GithubListSubIssuesRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
}

message GithubListSubIssuesResponse {
  bytes result_1 = 1;
}

message GithubListTeamInvitationsRequest {
  string org = 1;
  string team_slug = 2;
}

message GithubListTeamInvitationsResponse {
  bytes result_1 = 1;
}

message GithubListTeamReposRequest {
  string org = 1;
  string team_slug = 2;
}

message GithubListTeamReposResponse {
  bytes result_1 = 1;
}

message GithubListTeamsForRoleRequest {
  string org = 1;
  int64 role_id = 2;
}

message GithubListTeamsForRoleResponse {
  bytes result_1 = 1;
}

message GithubListUserEventsRequest {
  string username = 1;
}

message GithubListUserEventsResponse {
  bytes result_1 = 1;
}

message GithubListUserOrgMembershipsRequest {
}

message GithubListUserOrgMembershipsResponse {
  bytes result_1 = 1;
}

message GithubListUserTeamsRequest {
}

message GithubListUserTeamsResponse {
  bytes result_1 = 1;
}

message GithubListUsersForRoleRequest {
  string org = 1;
  int64 role_id = 2;
}

message GithubListUsersForRoleResponse {
  bytes result_1 = 1;
}

message GithubListWatchersRequest {
  string owner = 1;
  string repo = 2;
}

message GithubListWatchersResponse {
  bytes result_1 = 1;
}

message GithubLockIssueRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  string reason = 4;
}

message GithubLockIssueResponse {
}

message GithubLogoutRequest {
}

message GithubLogoutResponse {
}

message GithubMarkAllNotificationsReadRequest {
}

message GithubMarkAllNotificationsReadResponse {
}

message GithubMarkAsReadRequest {
  string chat_id = 1;
  string up_to_msg_id = 2;
}

message GithubMarkAsReadResponse {
}

message GithubMarkDiscussionCommentAsAnswerRequest {
  string comment_id = 1;
}

message GithubMarkDiscussionCommentAsAnswerResponse {
  bytes result_1 = 1;
}

message GithubMarkThreadReadRequest {
  string thread_id = 1;
}

message GithubMarkThreadReadResponse {
}

message GithubMarkUnreadRequest {
  string chat_id = 1;
  bool unread = 2;
}

message GithubMarkUnreadResponse {
}

message GithubMergePullRequestRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  string merge_method = 4;
  string commit_title = 5;
  string commit_message = 6;
}

message GithubMergePullRequestResponse {
  bytes result_1 = 1;
}

message GithubMuteChatRequest {
  string chat_id = 1;
  bool muted = 2;
}

message GithubMuteChatResponse {
}

message GithubNameRequest {
}

message GithubNameResponse {
  string result_1 = 1;
}

message GithubPinMessageRequest {
  string chat_id = 1;
  string msg_id = 2;
}

message GithubPinMessageResponse {
}

message GithubReactToMessageRequest {
  string chat_id = 1;
  string msg_id = 2;
  string emoji = 3;
}

message GithubReactToMessageResponse {
}

message GithubRemoveCollaboratorRequest {
  string owner = 1;
  string repo = 2;
  string username = 3;
}

message GithubRemoveCollaboratorResponse {
}

message GithubRemoveIssueAssigneesRequest {
  string owner = 1;
  string repo = 2;
  int64 issue_number = 3;
  bytes payload = 4;
}

message GithubRemoveIssueAssigneesResponse {
}

message GithubRemoveLabelRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  string label = 4;
}

message GithubRemoveLabelResponse {
}

message GithubRemoveMemberRequest {
  string chat_id = 1;
  string user_id = 2;
}

message GithubRemoveMemberResponse {
}

message GithubRemoveOrgInteractionLimitsRequest {
  string org = 1;
}

message GithubRemoveOrgInteractionLimitsResponse {
}

message GithubRemoveOrgMembershipRequest {
  string org = 1;
  string username = 2;
}

message GithubRemoveOrgMembershipResponse {
}

message GithubRemoveOutsideCollaboratorRequest {
  string org = 1;
  string username = 2;
}

message GithubRemoveOutsideCollaboratorResponse {
}

message GithubRemoveRepoInteractionLimitsRequest {
  string owner = 1;
  string repo = 2;
}

message GithubRemoveRepoInteractionLimitsResponse {
}

message GithubRemoveRequestedReviewersRequest {
  string owner = 1;
  string repo = 2;
  int64 pr_number = 3;
  bytes payload = 4;
}

message GithubRemoveRequestedReviewersResponse {
}

message GithubRemoveTeamMemberRequest {
  string org = 1;
  string team_slug = 2;
  string username = 3;
}

message GithubRemoveTeamMemberResponse {
}

message GithubRemoveTeamRepoRequest {
  string org = 1;
  string team_slug = 2;
  string owner = 3;
  string repo = 4;
}

message GithubRemoveTeamRepoResponse {
}

message GithubRemoveTeamRoleRequest {
  string org = 1;
  string team_slug = 2;
  int64 role_id = 3;
}

message GithubRemoveTeamRoleResponse {
}

message GithubRemoveUserInteractionLimitsRequest {
}

message GithubRemoveUserInteractionLimitsResponse {
}

message GithubRemoveUserRoleRequest {
  string org = 1;
  string username = 2;
  int64 role_id = 3;
}

message GithubRemoveUserRoleResponse {
}

message GithubReplyToMessageRequest {
  string chat_id = 1;
  string reply_to_msg_id = 2;
  uniclient.OutgoingMessage msg = 3;
}

message GithubReplyToMessageResponse {
  uniclient.Message result_1 = 1;
}

message GithubRequestReviewersRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  repeated string reviewers = 4;
  repeated string team_reviewers = 5;
}

message GithubRequestReviewersResponse {
  bytes result_1 = 1;
}

message GithubSearchGlobalRequest {
  string query = 1;
  uniclient.PaginationOpts opts = 2;
}

message GithubSearchGlobalResponse {
  repeated uniclient.Dialog result_1 = 1;
}

message GithubSearchIssuesAndPRsRequest {
  string query = 1;
  map<string, string> params = 2;
}

message GithubSearchIssuesAndPRsResponse {
  bytes result_1 = 1;
}

message GithubSearchMessagesRequest {
  string chat_id = 1;
  string query = 2;
  uniclient.PaginationOpts opts = 3;
}

message GithubSearchMessagesResponse {
  repeated uniclient.Message result_1 = 1;
}

message GithubSearchRepositoriesRequest {
  string query = 1;
  map<string, string> params = 2;
}

message GithubSearchRepositoriesResponse {
  bytes result_1 = 1;
}

message GithubSearchUsersRequest {
  string query = 1;
  map<string, string> params = 2;
}

message GithubSearchUsersResponse {
  bytes result_1 = 1;
}

message GithubSendImageBase64Request {
  string chat_id = 1;
  string b64 = 2;
  string caption = 3;
}

message GithubSendImageBase64Response {
  uniclient.Message result_1 = 1;
}

message GithubSendLocationRequest {
  string chat_id = 1;
  double lat = 2;
  double lon = 3;
}

message GithubSendLocationResponse {
  uniclient.Message result_1 = 1;
}

message GithubSendMessageRequest {
  string chat_id = 1;
  uniclient.OutgoingMessage msg = 2;
}

message GithubSendMessageResponse {
  uniclient.Message result_1 = 1;
}

message GithubSendStickerRequest {
  string chat_id = 1;
  string sticker_id = 2;
}

message GithubSendStickerResponse {
  uniclient.Message result_1 = 1;
}

message GithubSendTypingRequest {
  string param_1 = 1;
}

message GithubSendTypingResponse {
}

message GithubSetActiveChatRequest {
  string chat_id = 1;
}

message GithubSetActiveChatResponse {
}

message GithubSetAdminRequest {
  string chat_id = 1;
  string user_id = 2;
  bool admin = 3;
}

message GithubSetAdminResponse {
}

message GithubSetCallMutedRequest {
  string param_1 = 1;
  bool param_2 = 2;
}

message GithubSetCallMutedResponse {
}

message GithubSetLabelsRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  repeated string labels = 4;
}

message GithubSetLabelsResponse {
  bytes result_1 = 1;
}

message GithubSetOrgInteractionLimitsRequest {
  string org = 1;
  bytes payload = 2;
}

message GithubSetOrgInteractionLimitsResponse {
  bytes result_1 = 1;
}

message GithubSetOrgMembershipRequest {
  string org = 1;
  string username = 2;
  bytes payload = 3;
}

message GithubSetOrgMembershipResponse {
  bytes result_1 = 1;
}

message GithubSetRepoInteractionLimitsRequest {
  string owner = 1;
  string repo = 2;
  bytes payload = 3;
}

message GithubSetRepoInteractionLimitsResponse {
  bytes result_1 = 1;
}

message GithubSetRepoTopicsRequest {
  string owner = 1;
  string repo = 2;
  repeated string topics = 3;
}

message GithubSetRepoTopicsResponse {
  bytes result_1 = 1;
}

message GithubSetUserInteractionLimitsRequest {
  bytes payload = 1;
}

message GithubSetUserInteractionLimitsResponse {
  bytes result_1 = 1;
}

message GithubStarGistRequest {
  string gist_id = 1;
}

message GithubStarGistResponse {
}

message GithubStarRepoRequest {
  string owner = 1;
  string repo = 2;
}

message GithubStarRepoResponse {
}

message GithubStartCallRequest {
  string param_1 = 1;
  bool param_2 = 2;
}

message GithubStartCallResponse {
  uniclient.CallSession result_1 = 1;
}

message GithubSubmitPRReviewRequest {
  string owner = 1;
  string repo = 2;
  int64 pr_number = 3;
  int64 review_id = 4;
  string body = 5;
  string event = 6;
}

message GithubSubmitPRReviewResponse {
  bytes result_1 = 1;
}

message GithubSubscribeThreadRequest {
  string thread_id = 1;
}

message GithubSubscribeThreadResponse {
  bytes result_1 = 1;
}

message GithubTerminateSessionRequest {
  string param_1 = 1;
}

message GithubTerminateSessionResponse {
}

message GithubToggleCameraRequest {
  string param_1 = 1;
  bool param_2 = 2;
}

message GithubToggleCameraResponse {
}

message GithubTransferRepoRequest {
  string owner = 1;
  string repo = 2;
  string new_owner = 3;
}

message GithubTransferRepoResponse {
  bytes result_1 = 1;
}

message GithubUnbanMemberRequest {
  string chat_id = 1;
  string user_id = 2;
}

message GithubUnbanMemberResponse {
}

message GithubUnblockOrgUserRequest {
  string org = 1;
  string username = 2;
}

message GithubUnblockOrgUserResponse {
}

message GithubUnblockUserRequest {
  string user_id = 1;
}

message GithubUnblockUserResponse {
}

message GithubUnlockIssueRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
}

message GithubUnlockIssueResponse {
}

message GithubUnpinAllMessagesRequest {
  string chat_id = 1;
}

message GithubUnpinAllMessagesResponse {
}

message GithubUnpinMessageRequest {
  string chat_id = 1;
  string msg_id = 2;
}

message GithubUnpinMessageResponse {
}

message GithubUnstarGistRequest {
  string gist_id = 1;
}

message GithubUnstarGistResponse {
}

message GithubUnstarRepoRequest {
  string owner = 1;
  string repo = 2;
}

message GithubUnstarRepoResponse {
}

message GithubUnsubscribeThreadRequest {
  string thread_id = 1;
}

message GithubUnsubscribeThreadResponse {
}

message GithubUnwatchRepoRequest {
  string owner = 1;
  string repo = 2;
}

message GithubUnwatchRepoResponse {
}

message GithubUpdateCommitCommentRequest {
  string owner = 1;
  string repo = 2;
  int64 comment_id = 3;
  string body = 4;
}

message GithubUpdateCommitCommentResponse {
  bytes result_1 = 1;
}

message GithubUpdateDiscussionRequest {
  string discussion_id = 1;
  string title = 2;
  string body = 3;
}

message GithubUpdateDiscussionResponse {
  bytes result_1 = 1;
}

message GithubUpdateDiscussionCommentRequest {
  string comment_id = 1;
  string body = 2;
}

message GithubUpdateDiscussionCommentResponse {
  bytes result_1 = 1;
}

message GithubUpdateGistRequest {
  string gist_id = 1;
  string description = 2;
  bytes files = 3;
}

message GithubUpdateGistResponse {
  bytes result_1 = 1;
}

message GithubUpdateInvitationRequest {
  string owner = 1;
  string repo = 2;
  int64 invitation_id = 3;
  string permissions = 4;
}

message GithubUpdateInvitationResponse {
  bytes result_1 = 1;
}

message GithubUpdateLabelRequest {
  string owner = 1;
  string repo = 2;
  string name = 3;
  bytes updates = 4;
}

message GithubUpdateLabelResponse {
  bytes result_1 = 1;
}

message GithubUpdateMilestoneRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  bytes updates = 4;
}

message GithubUpdateMilestoneResponse {
  bytes result_1 = 1;
}

message GithubUpdateProfileRequest {
  string name = 1;
  string bio = 2;
  string blog = 3;
  string company = 4;
  string location = 5;
}

message GithubUpdateProfileResponse {
  bytes result_1 = 1;
}

message GithubUpdateProjectV2Request {
  string project_id = 1;
  bytes payload = 2;
}

message GithubUpdateProjectV2Response {
  bytes result_1 = 1;
}

message GithubUpdateProjectV2ItemRequest {
  string project_id = 1;
  string item_id = 2;
  string field_id = 3;
  bytes value = 4;
}

message GithubUpdateProjectV2ItemResponse {
  bytes result_1 = 1;
}

message GithubUpdatePullRequestRequest {
  string owner = 1;
  string repo = 2;
  int64 number = 3;
  bytes updates = 4;
}

message GithubUpdatePullRequestResponse {
  bytes result_1 = 1;
}

message GithubUpdateReleaseRequest {
  string owner = 1;
  string repo = 2;
  int64 release_id = 3;
  bytes updates = 4;
}

message GithubUpdateReleaseResponse {
  bytes result_1 = 1;
}

message GithubUpdateTeamRequest {
  string org = 1;
  string team_slug = 2;
  bytes updates = 3;
}

message GithubUpdateTeamResponse {
  bytes result_1 = 1;
}

message GithubUploadReleaseAssetRequest {
  string owner = 1;
  string repo = 2;
  int64 release_id = 3;
  string name = 4;
  bytes data = 5;
  string content_type = 6;
}

message GithubUploadReleaseAssetResponse {
  bytes result_1 = 1;
}

message GithubVotePollRequest {
  string chat_id = 1;
  string msg_id = 2;
  int64 option_index = 3;
}

message GithubVotePollResponse {
}

message GithubWatchRepoRequest {
  string owner = 1;
  string repo = 2;
}

message GithubWatchRepoResponse {
  bytes result_1 = 1;
}

