// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/cores/telegram_bar_settings.proto

package cores

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelegramGetPeerBarSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramGetPeerBarSettingsRequest) Reset() {
	*x = TelegramGetPeerBarSettingsRequest{}
	mi := &file_proto_cores_telegram_bar_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramGetPeerBarSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramGetPeerBarSettingsRequest) ProtoMessage() {}

func (x *TelegramGetPeerBarSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cores_telegram_bar_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramGetPeerBarSettingsRequest.ProtoReflect.Descriptor instead.
func (*TelegramGetPeerBarSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cores_telegram_bar_settings_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramGetPeerBarSettingsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type TelegramGetPeerBarSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result_1      string                 `protobuf:"bytes,1,opt,name=result_1,json=result1,proto3" json:"result_1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramGetPeerBarSettingsResponse) Reset() {
	*x = TelegramGetPeerBarSettingsResponse{}
	mi := &file_proto_cores_telegram_bar_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramGetPeerBarSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramGetPeerBarSettingsResponse) ProtoMessage() {}

func (x *TelegramGetPeerBarSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cores_telegram_bar_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramGetPeerBarSettingsResponse.ProtoReflect.Descriptor instead.
func (*TelegramGetPeerBarSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cores_telegram_bar_settings_proto_rawDescGZIP(), []int{1}
}

func (x *TelegramGetPeerBarSettingsResponse) GetResult_1() string {
	if x != nil {
		return x.Result_1
	}
	return ""
}

var File_proto_cores_telegram_bar_settings_proto protoreflect.FileDescriptor

const file_proto_cores_telegram_bar_settings_proto_rawDesc = "" +
	"\n" +
	"'proto/cores/telegram_bar_settings.proto\x12\x12uniclient.telegram\"<\n" +
	"!TelegramGetPeerBarSettingsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"?\n" +
	"\"TelegramGetPeerBarSettingsResponse\x12\x19\n" +
	"\bresult_1\x18\x01 \x01(\tR\aresult1B\x17Z\x15uniclient/proto/coresb\x06proto3"

var (
	file_proto_cores_telegram_bar_settings_proto_rawDescOnce sync.Once
	file_proto_cores_telegram_bar_settings_proto_rawDescData []byte
)

func file_proto_cores_telegram_bar_settings_proto_rawDescGZIP() []byte {
	file_proto_cores_telegram_bar_settings_proto_rawDescOnce.Do(func() {
		file_proto_cores_telegram_bar_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cores_telegram_bar_settings_proto_rawDesc), len(file_proto_cores_telegram_bar_settings_proto_rawDesc)))
	})
	return file_proto_cores_telegram_bar_settings_proto_rawDescData
}

var file_proto_cores_telegram_bar_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cores_telegram_bar_settings_proto_goTypes = []any{
	(*TelegramGetPeerBarSettingsRequest)(nil),  // 0: uniclient.telegram.TelegramGetPeerBarSettingsRequest
	(*TelegramGetPeerBarSettingsResponse)(nil), // 1: uniclient.telegram.TelegramGetPeerBarSettingsResponse
}
var file_proto_cores_telegram_bar_settings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cores_telegram_bar_settings_proto_init() }
func file_proto_cores_telegram_bar_settings_proto_init() {
	if File_proto_cores_telegram_bar_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cores_telegram_bar_settings_proto_rawDesc), len(file_proto_cores_telegram_bar_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cores_telegram_bar_settings_proto_goTypes,
		DependencyIndexes: file_proto_cores_telegram_bar_settings_proto_depIdxs,
		MessageInfos:      file_proto_cores_telegram_bar_settings_proto_msgTypes,
	}.Build()
	File_proto_cores_telegram_bar_settings_proto = out.File
	file_proto_cores_telegram_bar_settings_proto_goTypes = nil
	file_proto_cores_telegram_bar_settings_proto_depIdxs = nil
}
