// Generated by scripts/build_flutter.sh — do not edit manually.
const kAppVersion = '0.1.0';
const kAppStage = 'alpha';
const kAppStageNum = '';
const kBuildDate = '2026-06-06';

String get appVersionString {
  if (kAppStage.isEmpty) return kAppVersion;
  if (kAppStageNum.isEmpty) return '$kAppVersion-$kAppStage';
  return '$kAppVersion-$kAppStage.$kAppStageNum';
}
